version: '3'

services:

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    command: redis-server
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
